version: "3.9"

services:

  postgres:
    image: postgres:14
    container_name: delivery_service_db
    ports:
      - "5434:5432"
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "delivery_service"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"  # Порт для NATS
      - "4223:4223"  # Порт для NATS Streaming
      - "8222:8222"  # Порт для HTTP API
    environment:
      - NATS_CLUSTER_ID=test-cluster
      - NATS_STREAMING_PORT=4222
      - NATS_HTTP_PORT=8222
    restart: always

  delivery-service:
    image: service-image
    container_name: delivery_service
    build:
      dockerfile: Dockerfile
    command: [ "./wb" ]
    restart: always